### ISSUE TITLE
Update sources.txt for screenshots

### ISSUE THREAD

**Issue by hunderslash** [minecrafthistory/minecrafthistory.github.io#15]
I am extremely new to github so I don't know the right way to do this, but I added sources for many of the images in a forked repo :)

**Comment by hunderslash** [comment]
ok I figured it out lol

**Comment by nushiredev** [comment]
Thank you for the contribution, you PR has been merged :)

**Comment by hunderslash** [comment]
oh thank you! I just saw haha

**Comment by nushiredev** [comment]
lol
