### ISSUE TITLE
Missing links to archived originals

### ISSUE THREAD

**Issue by nushiredev** [minecrafthistory/minecrafthistory.github.io#3]

**Comment by nushiredev** [comment]
Kindly solved by @hunderslash :)

**Comment by hunderslash** [comment]
at least the ones between c0.0.9a and c0.0.12a_01. There are definitely more of them, in fact I have a work-in-progress spreadsheet for https://docs.google.com/spreadsheets/d/1vCrui6f_se_2F0lTf6ckPa8UNecdnxVctt96oJ7pdxk/

as for some of the later ones I can't say for certain, although I know the source of a few

**Comment by nushiredev** [comment]
@hunderslash Maybe we could make a gallery for these images? The website is still in it's early stages so experimentation is welcomed :)
